# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Gym.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Gym.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\tGym.proto\"\x1a\n\x04Gyms\x12\x12\n\x04gyms\x18\x01 \x03(\x0b\x32\x04.Gym\"Q\n\x03Gym\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0elarge_icon_url\x18\x02 \x01(\t\x12\x16\n\x06\x66loors\x18\x03 \x03(\x0b\x32\x06.Floor\x12\x0c\n\x04uuid\x18\x04 \x01(\t\"W\n\x05\x46loor\x12\x14\n\x05walls\x18\x01 \x03(\x0b\x32\x05.Wall\x12\x19\n\x07polygon\x18\x02 \x01(\x0b\x32\x08.Polygon\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\"G\n\x04Wall\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x07polygon\x18\x02 \x01(\x0b\x32\x08.Polygon\x12\x16\n\x06routes\x18\x03 \x03(\x0b\x32\x06.Route\"0\n\x07Polygon\x12\x16\n\x06points\x18\x01 \x03(\x0b\x32\x06.Point\x12\r\n\x05\x63olor\x18\x02 \x01(\t\"M\n\x05Route\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x08position\x18\x02 \x01(\x0b\x32\x06.Point\x12\r\n\x05grade\x18\x03 \x01(\x05\x12\r\n\x05\x63olor\x18\x04 \x01(\t\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x42\x17\n\x0f\x63om.peter.ClimbB\x04Msgsb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GYMS = _descriptor.Descriptor(
  name='Gyms',
  full_name='Gyms',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gyms', full_name='Gyms.gyms', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=39,
)


_GYM = _descriptor.Descriptor(
  name='Gym',
  full_name='Gym',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Gym.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='large_icon_url', full_name='Gym.large_icon_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='floors', full_name='Gym.floors', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='Gym.uuid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=122,
)


_FLOOR = _descriptor.Descriptor(
  name='Floor',
  full_name='Floor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='walls', full_name='Floor.walls', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='polygon', full_name='Floor.polygon', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='Floor.width', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='Floor.height', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=211,
)


_WALL = _descriptor.Descriptor(
  name='Wall',
  full_name='Wall',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Wall.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='polygon', full_name='Wall.polygon', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='routes', full_name='Wall.routes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=284,
)


_POLYGON = _descriptor.Descriptor(
  name='Polygon',
  full_name='Polygon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='Polygon.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='color', full_name='Polygon.color', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=334,
)


_ROUTE = _descriptor.Descriptor(
  name='Route',
  full_name='Route',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Route.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='Route.position', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grade', full_name='Route.grade', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='color', full_name='Route.color', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=413,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Point.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='Point.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=444,
)

_GYMS.fields_by_name['gyms'].message_type = _GYM
_GYM.fields_by_name['floors'].message_type = _FLOOR
_FLOOR.fields_by_name['walls'].message_type = _WALL
_FLOOR.fields_by_name['polygon'].message_type = _POLYGON
_WALL.fields_by_name['polygon'].message_type = _POLYGON
_WALL.fields_by_name['routes'].message_type = _ROUTE
_POLYGON.fields_by_name['points'].message_type = _POINT
_ROUTE.fields_by_name['position'].message_type = _POINT
DESCRIPTOR.message_types_by_name['Gyms'] = _GYMS
DESCRIPTOR.message_types_by_name['Gym'] = _GYM
DESCRIPTOR.message_types_by_name['Floor'] = _FLOOR
DESCRIPTOR.message_types_by_name['Wall'] = _WALL
DESCRIPTOR.message_types_by_name['Polygon'] = _POLYGON
DESCRIPTOR.message_types_by_name['Route'] = _ROUTE
DESCRIPTOR.message_types_by_name['Point'] = _POINT

Gyms = _reflection.GeneratedProtocolMessageType('Gyms', (_message.Message,), dict(
  DESCRIPTOR = _GYMS,
  __module__ = 'Gym_pb2'
  # @@protoc_insertion_point(class_scope:Gyms)
  ))
_sym_db.RegisterMessage(Gyms)

Gym = _reflection.GeneratedProtocolMessageType('Gym', (_message.Message,), dict(
  DESCRIPTOR = _GYM,
  __module__ = 'Gym_pb2'
  # @@protoc_insertion_point(class_scope:Gym)
  ))
_sym_db.RegisterMessage(Gym)

Floor = _reflection.GeneratedProtocolMessageType('Floor', (_message.Message,), dict(
  DESCRIPTOR = _FLOOR,
  __module__ = 'Gym_pb2'
  # @@protoc_insertion_point(class_scope:Floor)
  ))
_sym_db.RegisterMessage(Floor)

Wall = _reflection.GeneratedProtocolMessageType('Wall', (_message.Message,), dict(
  DESCRIPTOR = _WALL,
  __module__ = 'Gym_pb2'
  # @@protoc_insertion_point(class_scope:Wall)
  ))
_sym_db.RegisterMessage(Wall)

Polygon = _reflection.GeneratedProtocolMessageType('Polygon', (_message.Message,), dict(
  DESCRIPTOR = _POLYGON,
  __module__ = 'Gym_pb2'
  # @@protoc_insertion_point(class_scope:Polygon)
  ))
_sym_db.RegisterMessage(Polygon)

Route = _reflection.GeneratedProtocolMessageType('Route', (_message.Message,), dict(
  DESCRIPTOR = _ROUTE,
  __module__ = 'Gym_pb2'
  # @@protoc_insertion_point(class_scope:Route)
  ))
_sym_db.RegisterMessage(Route)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'Gym_pb2'
  # @@protoc_insertion_point(class_scope:Point)
  ))
_sym_db.RegisterMessage(Point)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\017com.peter.ClimbB\004Msgs'))
# @@protoc_insertion_point(module_scope)
